global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blackbox-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
  
  - job_name: 'blackbox-worker'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
